In [2]:
import numpy as np

In [53]:
a = np.array([[1],[2]])

In [54]:
a.shape

(2, 1)

In [55]:
if len(a.shape) == 1:
    ar = 1
    ac = a.shape[0]
else:
    ar,ac = a.shape

In [56]:
ar,ac

(2, 1)

In [57]:
%run linear_regression_test.py


======== Question 1.1 and Question 1.2 ========


AttributeError: 'NoneType' object has no attribute 'shape'

In [58]:
a = [-1,-2]

In [59]:
np.absolute(a)

array([1, 2])

In [64]:
a = [[0,0,0],[0,0,0],[0,0,0]]
b = [[0.1,0,0],[0,0.1,0],[0,0,0.1]]
np.add(a,b)

array([[0.1, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.1]])

In [65]:
10**-1 * np.identity(3)

array([[0.1, 0. , 0. ],
       [0. , 0.1, 0. ],
       [0. , 0. , 0.1]])

In [91]:
a = np.array([[1,2,3],[2,3,4],[3,4,5]])
#a.transpose()
print(a.T)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [92]:
x = np.arange(4).reshape((2,2))
np.transpose(x)
x

array([[0, 1],
       [2, 3]])

In [109]:
a = np.array([[[1,2,3]]])
a.T

array([[[1]],

       [[2]],

       [[3]]])

In [110]:
10**-5

1e-05

In [112]:
10**-1 * np.identity(12)

array([[0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.1]])

In [116]:
min([0.0000001, 1])

1e-07

In [117]:
lambda_range = range(-19,20,1)

In [119]:
for a in lambda_range:
    print(a)

-19
-18
-17
-16
-15
-14
-13
-12
-11
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [120]:
10**-1

0.1

In [136]:
a=[[1,2,3],[1,2,3],[1,2,3]]
np.insert(a,len(a[0]),[[2,3,4],[3,4,5],[4,5,6]], axis=1)


array([[1, 2, 3, 2, 3, 4],
       [1, 2, 3, 3, 4, 5],
       [1, 2, 3, 4, 5, 6]])

In [157]:
a=[[1,2,3],[1,2,3]]
# for row in np.power(a,2):
#     np.insert(a[0],len(a[0])-1,row)
np.insert(a,[len(a[0])],np.power(a,2), axis=1)


array([[1, 2, 3, 1, 4, 9],
       [1, 2, 3, 1, 4, 9]])

In [159]:
np.insert(a,[len(a[0])],np.power(a,2), axis=1)

array([[1, 2, 3, 1, 4, 9],
       [1, 2, 3, 1, 4, 9]])

In [155]:
np.power(a,2)

array([[1, 4, 9],
       [1, 4, 9]])

In [ ]:
np.insert(a,[len(a[0])-1],np.power(a,2), axis=1)

In [160]:
for j in range(2):
    print(j)

0
1


In [190]:
a = [[0],[0]]
b = [[1,2,3],[1,2,3]]
np.multiply(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [170]:
w = np.array([0.3, 0.7])
x = np.array([[1,2], [2,3]])
s2=np.matmul(x,np.array([w]).T)

In [171]:
s1+s2

array([[1.4],
       [3. ]])

In [176]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [181]:
a = [[-1],[1]]
tmp = np.array(a)
result = []
for j in tmp:
    if j <= 0:
        result.append(1)
    else:
        result.append(0)
np.array([result])

array([[1, 0]])

In [185]:
x = [[1],[0]]
y = [[1,2,3],[1,2,3]]
np.sum(np.multiply(x,y),axis=1)

array([6, 0])

In [188]:
np.array(x).flatten() / 3

array([0.33333333, 0.        ])

In [194]:
np.zeros((1,325))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [198]:
a

[[0], [0]]

In [202]:
np.zeros((1,2))

array([[0., 0.]])

In [205]:
np.matmul(np.ones((1,2)),a)

array([[0.]])

In [206]:
True ? 1; 0

SyntaxError: invalid syntax (<ipython-input-206-1be04dd81753>, line 1)

In [4]:
np.random.choice(305,305)

TypeError: choice() takes at least 1 positional argument (0 given)

In [8]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([2,0,2])
a[b]

array([[7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])